# 公開するページのURL
baseURL = "https://toko64.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "ほげほげ"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "toko64"
    bio = "こんにちわわ"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "toko64"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "toko6464"
  github = "tko64"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

